"""no-op checkpoint after manual wholesale schema

Revision ID: 0452b411b674
Revises: 109251b64c06
Create Date: 2026-10-04 14:12:25.358891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0452b411b674'
down_revision = '109251b64c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cart_item_wholesale_id'), ['wholesale_id'], unique=False)
        batch_op.create_foreign_key(None, 'wholesale_account', ['wholesale_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cart_item_wholesale_id'))

    # ### end Alembic commands ###
