"""User: wholesale application and tier fields

Revision ID: 109251b64c06
Revises: f4a4cd5fcd66
Create Date: 2026-10-04 13:21:12.647258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '109251b64c06'
down_revision = 'f4a4cd5fcd66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_wholesale', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('wholesale_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('business_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('business_type', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('business_registration', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('wholesale_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('wholesale_applied_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('wholesale_approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('wholesale_tier', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_is_wholesale'), ['is_wholesale'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_is_wholesale'))
        batch_op.drop_column('wholesale_tier')
        batch_op.drop_column('wholesale_approved_at')
        batch_op.drop_column('wholesale_applied_at')
        batch_op.drop_column('wholesale_notes')
        batch_op.drop_column('business_registration')
        batch_op.drop_column('business_type')
        batch_op.drop_column('business_name')
        batch_op.drop_column('wholesale_status')
        batch_op.drop_column('is_wholesale')

    # ### end Alembic commands ###
