"""extend Product: long_description, gallery, tags, meta, active, updated_at, etc.

Revision ID: 58c379ccda99
Revises: c2440f515962
Create Date: 2026-10-04 10:48:36.451977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c379ccda99'
down_revision = 'c2440f515962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('long_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('compare_at_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gallery', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('stock_alert_threshold', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('meta_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('meta_description', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_product_active'), ['active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_active'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('active')
        batch_op.drop_column('meta_description')
        batch_op.drop_column('meta_title')
        batch_op.drop_column('tags')
        batch_op.drop_column('stock_alert_threshold')
        batch_op.drop_column('gallery')
        batch_op.drop_column('compare_at_price')
        batch_op.drop_column('long_description')

    # ### end Alembic commands ###
