"""extend User: profile fields, last_login, is_active_account

Revision ID: b651ebf3d8c4
Revises: 58c379ccda99
Create Date: 2026-10-04 11:15:49.414626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b651ebf3d8c4'
down_revision = '58c379ccda99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active_account', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('address_line', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('country')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('city')
        batch_op.drop_column('address_line')
        batch_op.drop_column('phone')
        batch_op.drop_column('full_name')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('is_active_account')

    # ### end Alembic commands ###
