"""add Article table for blog

Revision ID: f4a4cd5fcd66
Revises: b651ebf3d8c4
Create Date: 2026-10-04 13:18:04.537374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a4cd5fcd66'
down_revision = 'b651ebf3d8c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=True),
    sa.Column('excerpt', sa.String(length=400), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('hero_image', sa.String(length=300), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('tags', sa.String(length=400), nullable=True),
    sa.Column('author_name', sa.String(length=120), nullable=True),
    sa.Column('reading_minutes', sa.Integer(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('meta_title', sa.String(length=250), nullable=True),
    sa.Column('meta_description', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_published'), ['published'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_slug'), ['slug'], unique=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('unit_quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('allow_custom_weight', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('allow_custom_weight')
        batch_op.drop_column('unit_quantity')
        batch_op.drop_column('unit')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_slug'))
        batch_op.drop_index(batch_op.f('ix_article_published'))
        batch_op.drop_index(batch_op.f('ix_article_category'))

    op.drop_table('article')
    # ### end Alembic commands ###
